Backport PXC-3076: Galera build doesn't work with Python 3
Issue:
The main SConstruct contains an incorrect Python 3 specific code
and results in an error.

  AttributeError: 'str' object has no attribute 'decode'

Fix:
Remove the python3 specific code and everything works with all scons
versions tested

(cherry picked from commit a3bc6ec232e7cc8ad5dba5f44898e007fb587725)